// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, name, birth, email, location, active
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, name, birth, email, location, created_at, updated_at, active
`

type CreateUserParams struct {
	ID       string
	Name     string
	Birth    pgtype.Date
	Email    pgtype.Text
	Location pgtype.Text
	Active   bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Birth,
		arg.Email,
		arg.Location,
		arg.Active,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Birth,
		&i.Email,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
RETURNING id, name, birth, email, location, created_at, updated_at, active
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, birth, email, location, created_at, updated_at, active FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Birth,
		&i.Email,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, name, birth, email, location, created_at, updated_at, active FROM users
WHERE id IN ($1)
`

func (q *Queries) GetUsers(ctx context.Context, id string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Birth,
			&i.Email,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT id, name, birth, email, location, created_at, updated_at, active FROM users
WHERE active
ORDER BY name
`

func (q *Queries) ListActiveUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Birth,
			&i.Email,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, birth, email, location, created_at, updated_at, active FROM users
ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Birth,
			&i.Email,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
  name = CASE WHEN $2::boolean
  THEN $3 ELSE name END,

  birth = CASE WHEN $4::boolean
  THEN $5 ELSE birth END,

  email = CASE WHEN $6::boolean
  THEN $7 ELSE email END,

  location = CASE WHEN $8::boolean
  THEN $9 ELSE location END,

  active = CASE WHEN $10::boolean
  THEN $11 ELSE active END
WHERE id = $1
RETURNING id, name, birth, email, location, created_at, updated_at, active
`

type UpdateUserParams struct {
	ID               string
	NameDoUpdate     bool
	Name             string
	BirthDoUpdate    bool
	Birth            pgtype.Date
	EmailDoUpdate    bool
	Email            pgtype.Text
	LocationDoUpdate bool
	Location         pgtype.Text
	ActiveDoUpdate   bool
	Active           bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.NameDoUpdate,
		arg.Name,
		arg.BirthDoUpdate,
		arg.Birth,
		arg.EmailDoUpdate,
		arg.Email,
		arg.LocationDoUpdate,
		arg.Location,
		arg.ActiveDoUpdate,
		arg.Active,
	)
	return err
}
